@extends('layouts.buyer')

@push('styles')
    @vite(['resources/css/dashboard-buyer.css'])
@endpush

@push('scripts')
    @vite(['resources/js/dashboard.js'])
@endpush

@section('content')
    @php
        use Illuminate\Support\Str;

        $resolveImage = function ($url) {
            $url = (string) $url;
            if ($url === '') {
                return 'https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80';
            }
            if (Str::startsWith($url, ['http://', 'https://'])) {
                return $url;
            }
            if (Str::startsWith($url, 'storage/')) {
                return asset($url);
            }
            return asset('storage/' . ltrim($url, '/'));
        };
    @endphp

    {{-- CONFIG untuk JS (JANGAN diubah logikanya) --}}
    <script>
        window.heroSlides = @json($heroSlides ?? []);

        // Jika kamu sudah punya categoriesUi dari controller (DB-driven), inject di sini.
        // Kalau belum ada, JS kamu akan fallback ke categories default.
        window.categories = @json($categoriesUi ?? []);

        window.DASHBOARD_CFG = Object.assign({}, window.DASHBOARD_CFG || {}, {
            csrf: @json(csrf_token()),
            cartAddUrl: @json(route('cart.add')),
            favToggleUrl: @json(route('favorites.toggle')),
        });
    </script>

    <!-- =========================
             DASHBOARD WRAPPER
             ========================= -->
    <div class="dashboard-wrapper">

        {{-- Decorative shapes (tetap, cuma ditata lewat CSS nanti) --}}
        <div class="deco-shape deco-shape-1" aria-hidden="true"></div>
        <div class="deco-shape deco-shape-2" aria-hidden="true"></div>
        <div class="deco-shape deco-shape-3" aria-hidden="true"></div>

        <!-- =========================
                 HERO SECTION
                 ========================= -->
        <section class="hero-section">
            <div class="hero-container">
                {{-- Hero banner akan diisi oleh JS (buildHero) --}}
                <div class="hero-banner" id="heroBanner"></div>

                {{-- Dots will be generated by JS --}}
                <div class="hero-dots" id="heroDots"></div>

                {{-- Optional: Scroll indicator --}}
                <div class="scroll-indicator" aria-hidden="true">Scroll</div>
            </div>
        </section>

        <!-- =========================
                 CATEGORIES SECTION
                 ========================= -->
        <section class="categories-section">
            <div class="section-container">
                <!-- Head: title + subtitle jadi 1 cluster (nggak nyasar) -->
                <header class="section-head">
                    <div class="section-head-left">
                        <h2 class="categories-title">Browse Categories</h2>
                        <p class="section-subtitle">Find your favorite products by category</p>
                    </div>
                </header>

                <div class="content-container">
                    {{-- Grid akan diisi JS --}}
                    <div class="categories-grid" id="categoriesGrid"></div>
                </div>
            </div>
        </section>

        <!-- =========================
                 FLASH SALE SECTION
                 ========================= -->
        <section class="flash-sale-section" id="flash-sale">
            <div class="section-container">
                <header class="section-head section-head--row">
                    <!-- Left: title + timer -->
                    <div class="section-head-left">
                        <div class="section-title">
                            <i class="fas fa-bolt flash-icon" aria-hidden="true"></i>
                            <h2>Flash Sale</h2>

                            <div class="countdown-timer" aria-label="Countdown timer">
                                <i class="fas fa-clock timer-icon" aria-hidden="true"></i>
                                <div class="timer-display" id="countdownTimer">24:00:00</div>
                            </div>
                        </div>

                        <p class="section-subtitle">Limited-time deals on near-expiry foods</p>
                    </div>

                    <!-- Right: action -->
                    <div class="section-head-right">
                        <a href="/flash-sale" class="see-more-btn">
                            See More <i class="fas fa-arrow-right" aria-hidden="true"></i>
                        </a>
                    </div>
                </header>

                <div class="content-container">
                    <div class="swiper-container">
                        <div class="swiper" id="flashSaleSwiper">
                            <div class="swiper-wrapper" id="flashSaleProducts">
                                @if (isset($flashSaleProducts) && $flashSaleProducts->count() > 0)
                                    @foreach ($flashSaleProducts as $product)
                                        <div class="swiper-slide">
                                            <div class="product-card"
                                                onclick="window.location.href='{{ route('product.show', $product->id) }}'">

                                                <span class="flash-badge">Flash Sale</span>

                                                {{-- Urgency badge --}}
                                                @if ((int) $product->expiry_days <= 1)
                                                    <span class="food-urgency-badge">
                                                        <i class="fas fa-exclamation-triangle" aria-hidden="true"></i>
                                                        Expiring Today!
                                                    </span>
                                                @elseif((int) $product->expiry_days <= 3)
                                                    <span class="food-urgency-badge">
                                                        <i class="fas fa-clock" aria-hidden="true"></i>
                                                        Expiring Soon
                                                    </span>
                                                @endif

                                                <div class="product-image-container">
                                                    <img src="{{ $resolveImage($product->image_url) }}"
                                                        alt="{{ $product->name }}" class="product-image">

                                                    <div class="product-actions">
                                                        <button class="favorite-btn" type="button"
                                                            data-product-id="{{ $product->id }}"
                                                            onclick="toggleFavorite({{ $product->id }}); event.stopPropagation();"
                                                            aria-label="Toggle favorite">
                                                            <i class="far fa-heart" aria-hidden="true"></i>
                                                        </button>
                                                    </div>
                                                </div>

                                                <div class="product-info">
                                                    <div class="product-brand">
                                                        <i class="fas fa-store" aria-hidden="true"></i>
                                                        {{ $product->brand }}
                                                    </div>

                                                    <h3 class="product-name">{{ $product->name }}</h3>

                                                    <span class="product-category">{{ ucfirst($product->category) }}</span>

                                                    <div class="expiry-info">
                                                        <i class="fas fa-hourglass-half" aria-hidden="true"></i>
                                                        Expires in {{ (int) $product->expiry_days }} day(s)
                                                    </div>

                                                    <div class="location-info">
                                                        <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                                                        Available
                                                    </div>

                                                    <div class="product-rating">
                                                        <div class="stars" aria-label="Product rating">
                                                            @for ($i = 1; $i <= 5; $i++)
                                                                @if ($i <= floor((float) $product->rating))
                                                                    <i class="fas fa-star" aria-hidden="true"></i>
                                                                @elseif($i - 0.5 <= (float) $product->rating)
                                                                    <i class="fas fa-star-half-alt" aria-hidden="true"></i>
                                                                @else
                                                                    <i class="far fa-star" aria-hidden="true"></i>
                                                                @endif
                                                            @endfor
                                                        </div>
                                                        <span class="rating-count">
                                                            ({{ number_format((int) $product->rating_count) }})
                                                        </span>
                                                    </div>

                                                    <div class="product-price">
                                                        <div class="price-container">
                                                            <span class="current-price">
                                                                Rp{{ number_format((int) $product->price, 0, ',', '.') }}
                                                            </span>
                                                            <div class="price-meta">
                                                                <span class="original-price">
                                                                    Rp{{ number_format((int) $product->original_price, 0, ',', '.') }}
                                                                </span>
                                                                <span class="discount-percent">
                                                                    -{{ (int) $product->discount_percent }}%
                                                                </span>
                                                            </div>
                                                        </div>

                                                        <button type="button" class="add-to-cart-btn js-add-to-cart"
                                                            data-product-id="{{ $product->id }}"
                                                            onclick="event.preventDefault(); event.stopPropagation(); addToCart(event, {{ $product->id }});"
                                                            style="position:relative; z-index:50;"
                                                            aria-label="Add to cart">
                                                            <i class="fas fa-shopping-cart" aria-hidden="true"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                @else
                                    <div class="swiper-slide">
                                        <div class="product-card">
                                            <span class="flash-badge">Coming Soon</span>

                                            <div class="product-image-container">
                                                <img src="https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"
                                                    alt="No Products" class="product-image">

                                                <div class="product-actions">
                                                    <button class="favorite-btn" type="button"
                                                        onclick="event.stopPropagation()" aria-label="Favorite">
                                                        <i class="far fa-heart" aria-hidden="true"></i>
                                                    </button>
                                                </div>
                                            </div>

                                            <div class="product-info">
                                                <div class="product-brand">
                                                    <i class="fas fa-store" aria-hidden="true"></i> LastBite
                                                </div>
                                                <h3 class="product-name">More Flash Sale Products Coming Soon!</h3>
                                                <span class="product-category">Stay Tuned</span>

                                                <div class="product-rating">
                                                    <div class="stars">
                                                        <i class="fas fa-star" aria-hidden="true"></i>
                                                        <i class="fas fa-star" aria-hidden="true"></i>
                                                        <i class="fas fa-star" aria-hidden="true"></i>
                                                        <i class="fas fa-star" aria-hidden="true"></i>
                                                        <i class="fas fa-star-half-alt" aria-hidden="true"></i>
                                                    </div>
                                                    <span class="rating-count">(0)</span>
                                                </div>

                                                <div class="product-price">
                                                    <div class="price-container">
                                                        <span class="current-price">Check Back Later</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            </div>

                            <div class="swiper-button-next" aria-label="Next"></div>
                            <div class="swiper-button-prev" aria-label="Previous"></div>
                        </div>

                        <div class="flash-sale-dots" id="flashSaleDots"></div>
                    </div>
                </div>
            </div>
        </section>

        <!-- =========================
                 RECOMMENDED SECTION
                 ========================= -->
        <section class="recommended-section" id="recommendations">
            <div class="section-container">
                <header class="section-head">
                    <div class="section-head-left">
                        <div class="section-title">
                            <i class="fas fa-star star-icon" aria-hidden="true"></i>
                            <h2>Recommended Foods</h2>
                        </div>
                        <p class="section-subtitle">Carefully selected products based on your preferences</p>
                    </div>
                </header>

                <div class="content-container">
                    <div class="recommended-grid" id="recommendedGrid">
                        @if (isset($recommendedProducts) && count($recommendedProducts) > 0)
                            @foreach ($recommendedProducts as $product)
                                <div class="product-card"
                                    onclick="window.location.href='{{ route('product.show', $product->id) }}'">

                                    @if (!empty($product->is_flash_sale))
                                        <span class="flash-badge">Flash Sale</span>
                                    @else
                                        <span class="recommended-badge">Recommended</span>
                                    @endif

                                    @if ((int) $product->expiry_days <= 1)
                                        <span class="food-urgency-badge">
                                            <i class="fas fa-exclamation-triangle" aria-hidden="true"></i>
                                            Expiring Today!
                                        </span>
                                    @elseif((int) $product->expiry_days <= 3)
                                        <span class="food-urgency-badge">
                                            <i class="fas fa-clock" aria-hidden="true"></i>
                                            Expiring Soon
                                        </span>
                                    @endif

                                    <div class="product-image-container">
                                        <img src="{{ $resolveImage($product->image_url) }}" alt="{{ $product->name }}"
                                            class="product-image">

                                        <div class="product-actions">
                                            <button class="favorite-btn" type="button"
                                                data-product-id="{{ $product->id }}"
                                                onclick="toggleFavorite({{ $product->id }}); event.stopPropagation();"
                                                aria-label="Toggle favorite">
                                                <i class="far fa-heart" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                    </div>

                                    <div class="product-info">
                                        <div class="product-brand">
                                            <i class="fas fa-store" aria-hidden="true"></i>
                                            {{ $product->brand }}
                                        </div>

                                        <h3 class="product-name">{{ $product->name }}</h3>
                                        <span class="product-category">{{ ucfirst($product->category) }}</span>

                                        <div class="expiry-info">
                                            <i class="fas fa-hourglass-half" aria-hidden="true"></i>
                                            Expires in {{ (int) $product->expiry_days }} day(s)
                                        </div>

                                        <div class="location-info">
                                            <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                                            Available
                                        </div>

                                        <div class="product-rating">
                                            <div class="stars" aria-label="Product rating">
                                                @for ($i = 1; $i <= 5; $i++)
                                                    @if ($i <= floor((float) $product->rating))
                                                        <i class="fas fa-star" aria-hidden="true"></i>
                                                    @elseif($i - 0.5 <= (float) $product->rating)
                                                        <i class="fas fa-star-half-alt" aria-hidden="true"></i>
                                                    @else
                                                        <i class="far fa-star" aria-hidden="true"></i>
                                                    @endif
                                                @endfor
                                            </div>
                                            <span class="rating-count">
                                                ({{ number_format((int) $product->rating_count) }})
                                            </span>
                                        </div>

                                        <div class="product-price">
                                            <div class="price-container">
                                                <span class="current-price">
                                                    Rp{{ number_format((int) $product->price, 0, ',', '.') }}
                                                </span>
                                                <div class="price-meta">
                                                    <span class="original-price">
                                                        Rp{{ number_format((int) $product->original_price, 0, ',', '.') }}
                                                    </span>
                                                    <span class="discount-percent">
                                                        -{{ (int) $product->discount_percent }}%
                                                    </span>
                                                </div>
                                            </div>

                                            <button type="button" class="add-to-cart-btn"
                                                onclick="addToCart(event, {{ $product->id }})" aria-label="Add to cart">
                                                <i class="fas fa-shopping-cart" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @else
                            <div class="product-card">
                                <span class="recommended-badge">Recommended</span>

                                <div class="product-image-container">
                                    <img src="https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"
                                        alt="No Products" class="product-image">

                                    <div class="product-actions">
                                        <button class="favorite-btn" type="button" onclick="event.stopPropagation()"
                                            aria-label="Favorite">
                                            <i class="far fa-heart" aria-hidden="true"></i>
                                        </button>
                                    </div>
                                </div>

                                <div class="product-info">
                                    <div class="product-brand">
                                        <i class="fas fa-store" aria-hidden="true"></i> LastBite
                                    </div>
                                    <h3 class="product-name">More Recommended Products Coming Soon!</h3>
                                    <span class="product-category">Stay Tuned</span>

                                    <div class="product-rating">
                                        <div class="stars">
                                            <i class="fas fa-star" aria-hidden="true"></i>
                                            <i class="fas fa-star" aria-hidden="true"></i>
                                            <i class="fas fa-star" aria-hidden="true"></i>
                                            <i class="fas fa-star" aria-hidden="true"></i>
                                            <i class="fas fa-star-half-alt" aria-hidden="true"></i>
                                        </div>
                                        <span class="rating-count">(0)</span>
                                    </div>

                                    <div class="product-price">
                                        <div class="price-container">
                                            <span class="current-price">Check Back Later</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </section>

    </div><!-- End .dashboard-wrapper -->

    {{-- Auto-scroll to recommendations (tetap aman, tidak ganggu logic) --}}
    @if (session('scroll_to') === 'recommendations')
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                const target = document.getElementById('recommendations');
                if (target) {
                    setTimeout(() => {
                        target.scrollIntoView({
                            behavior: 'smooth',
                            block: 'start'
                        });
                    }, 150);
                }
            });
        </script>
    @endif

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const hash = window.location.hash;
            if (hash === '#recommendations') {
                const target = document.getElementById('recommendations');
                if (target) setTimeout(() => target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                }), 150);
            }
        });
    </script>
@endsection
